### ISSUE TITLE
The numeric gradient check failed!

### ISSUE THREAD

**Issue by Ellebkey** [jorgenkg/python-neural-network#12]
Hello I'm checking the library and I got a problem when I set my own data.

I'm creating a network with 48inputs, 30hidden layes and 2 for output. My inputs consist on values between 0-100. When I run the examples with my training data, the programs stops working and I get the error: The numeric gradient check failed!. I printed the diferrents values on gradient() and check_gradient() and I got nan on many values. 

Hope you can help me.

**Comment by jorgenkg** [comment]
Hi!
What have you specified as the activation functions?
If you're able to post a MVC of your data? If so it'll be even easier to help you out.

**Comment by Ellebkey** [comment]
I used the same example main.py  on the settings I put

settings            = {
    # Required settings
    "n_inputs"              : 48,   
    "layers"                : [  (30, sigmoid_function), (2, sigmoid_function) ],
    "weights_low"           : -1.0,    
    "weights_high"          : 1.0,     
}

My entries look like this:
                       Instance([0,0,0,13,5,0,0,0,0,0,0,59,44,0,0,0,0,0,2,99,88,0,0,0,0,0,1,90,80,0,0,0,0,0,0,63,54,0,0,0,0,0,0,44,44,0,0,0], [0,1])
.
.
.

But when I run the code stop on the line: 
network.check_gradient( training_data, cost_function ) 
and gives me that error

**Comment by jorgenkg** [comment]
Ok, it looks like the error was located in the preprocessors. I guess you've used the `standarize` preprocessor?

If that was the case, both the Github repo and the `pip`-installable version has been fixed!

**Comment by Ellebkey** [comment]
Yes, I used this:

preprocess          = construct_preprocessor( dataset, [standarize] ) 
training_data       = preprocess( dataset )
test_data           = preprocess( dataset )

I'll try to use the new fix

**Comment by Ellebkey** [comment]
Thanks you so much! It worked

**Comment by jorgenkg** [comment]
Good to hear! Thank you for making me aware of the issue!
