### ISSUE TITLE
ImportError: No module named learning_algorithms

### ISSUE THREAD

**Issue by chmdznr** [jorgenkg/python-neural-network#13]
after installing nimblenet via pip or github and trying to run the example code, I got these:
`Traceback (most recent call last):
  File "ann_nimble.py", line 3, in <module>
    from nimblenet.learning_algorithms import RMSprop
ImportError: No module named learning_algorithms`

Why?

**Comment by jorgenkg** [comment]
I'll take a look in 5 minutes

**Comment by jorgenkg** [comment]
Thank you for making me aware! 

The problem was that some of the nimblenet package names was left out from the setup.py configuration file.

Both pip and git has now been updated and verified
