### ISSUE TITLE
ImportError: No module named 'scaled_conjugate_gradient'

### ISSUE THREAD

**Issue by ashrafzia** [jorgenkg/python-neural-network#18]
Using python 3 i get the following error:

Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from nimblenet.learning_algorithms import *
  File "python-neural-network/nimblenet/learning_algorithms/__init__.py", line 2, in <module>
    from scaled_conjugate_gradient import scaled_conjugate_gradient
ImportError: No module named 'scaled_conjugate_gradient'

I got same error on my desktop but i don't know what i changed that it vanished but now on my laptop after installing i have same issue.

**Comment by jorgenkg** [comment]
Unfortunately, this library is written in Python 2.7 and thus will not run correctly with a Python 3 interpreter. Have  you tried installing the lib in a python 2 environment?

**Comment by ashrafzia** [comment]
I didn't tried with Python 2.7 but on my desktop am using Python 3.5.2 and it works. I remember i had same issue but i don't know what i installed or changed that it was fixed. I think it removed with installing PyPi JIT compiler but still not sure.
