### ISSUE TITLE
Support for python 3.+

### ISSUE THREAD

**Issue by NEGU93** [jorgenkg/python-neural-network#20]
I got the following:
```
Traceback (most recent call last):
  File "C:/Users/josea/Dropbox/ITBA/Redes Neuronales/ECG/src/main.py", line 5, in <module>
    from nimblenet.neuralnet import NeuralNet
  File "C:\Anaconda3\lib\site-packages\nimblenet\neuralnet.py", line 126
    print "[gradient check] Running gradient check..."
                                                     ^
SyntaxError: Missing parentheses in call to 'print'
```

This means of course that the program is for python 2.+ only.. will it be a version for python 3.+?

**Comment by jorgenkg** [comment]
Hi, I believe @fabikw has made a python 3 friendly fork of this project, but I've not tested it myself. 

https://github.com/fabikw/python-neural-network

**Comment by fabikw** [comment]
I've made a fork, but haven't been able to put much work on it.

**Comment by NEGU93** [comment]
Thank you for the quick answer!

I'll give it a try.

**Comment by xuiqzy** [comment]
The link to the fork is dead.
Is there any similar library to use for python 3 to build a neural net yourself in a low level kind of way, but with access to the common functions needed for error, learning, etc?
