### ISSUE TITLE
Copy-pasted example code from README

### ISSUE THREAD

**Issue by mvrozanti** [jorgenkg/python-neural-network#23]
After 150.000 epochs I understood that this is not working as expected -- it doesn't diminish the error.

**Comment by jorgenkg** [comment]
Learning the XOR is a complex task if the network is only given a with few nodes to work with. Try to increase the number of nodes in the hidden layer or restart the learning process. 

The math behind the network is correct.

**Comment by mvrozanti** [comment]
It was my fault. I set up something wrong. Ran it again and done in a second!

Great work sorry for the alarm

**Comment by jorgenkg** [comment]
That's ok. Feel free to post any questions if you run into trouble
