### ISSUE TITLE
Does not work on machine

### ISSUE THREAD

**Issue by supernerdhelloworld** [jorgenkg/python-neural-network#24]
Tried `pip install nimblenet`, got this error:

`Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/84/6yjtvl8s52jc3k8lf41chkn40000gn/T/pip-build-rLoiFl/nimblenet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/84/6yjtvl8s52jc3k8lf41chkn40000gn/T/pip-bVsSSv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/84/6yjtvl8s52jc3k8lf41chkn40000gn/T/pip-build-rLoiFl/nimblenet`

**Comment by wizzwizz4** [comment]
Which version of Python are you using?

**Comment by jorgenkg** [comment]
I’m closing this issue due to lack of debuggable info from the OP
