### ISSUE TITLE
can be use with integer/float > 1 ?

### ISSUE THREAD

**Issue by ryzenX** [jorgenkg/python-neural-network#25]
Hello, it's possible to use your neural network for addition of integer/float with result > 1 ?
like this : 
```
training_set_inputs = array([[2,1],[3,2],[1,4],[4,3],[2,4]])
training_set_outputs = array([[3,5,5,7,6]]).T
```

when i search 1+3:
`neural_network.forward_pass(array([1,3]))`

i have in output 0.99, what do I have to change in the code to do that?

**Comment by jorgenkg** [comment]
Yes. However, you cannot use an activation function that squashes the output signal to the interval [0,1] in the output layer like eg. the sigmoidal activation function does.

Maybe the ReLU activation function will work for your application.
