### ISSUE TITLE
How do I import a CSV file

### ISSUE THREAD

**Issue by davidrimshnick** [jorgenkg/python-neural-network#26]
Sorry I can't seem to find in the documentation...

**Comment by jorgenkg** [comment]
The library does not provide any means to import CSV files nor any other arbitrary file formats. 

To import the CSV file content, you’ll have to use vanilla python code and read the file content. Eg:

```
with open(“file.csv”, “r”) as f:
   csv_content = f.read()
```

**Comment by wizzwizz4** [comment]
Alternatively, you can make use of the [`csv`](https://docs.python.org/library/csv.html) module.

**Comment by davidrimshnick** [comment]
That's fine.. Maybe I am missing the documentation on how to convert these
to "instances"?  I don't see the documentation on how to create the
instances other than hardcoding the data.

Really appreciate the library by the way!

**Comment by wizzwizz4** [comment]
Can this be modified to do what you want?

    csv_data = [[[0, 0], [0]], [[1, 0], [1]], [[0, 1], [1]], [[1, 1], [0]]]
    dataset = [Instance(inputs, outputs) for (inputs, outputs) in csv_data]

**Comment by davidrimshnick** [comment]
I will try that, thank you.
