### ISSUE TITLE
Example tests on training set

### ISSUE THREAD

**Issue by wizzwizz4** [jorgenkg/python-neural-network#27]
The example tests on the same dataset that it trains on. This makes it liable to overfitting.

There's no way around it for this specific example, unfortunately; perhaps the example could be changed to make it possible to demonstrate without having this flaw?

**Comment by jorgenkg** [comment]
Correct, albeit solving the XOR problem is a famous neural network problem. The example illustrate how a neural network can be specified along with its error and activation functions. Hence, the example is no flaw - only a minimal and verifiable example of how to apply the library
