### ISSUE TITLE
Attempting tranpose on int returned from linear_function

### ISSUE THREAD

**Issue by huntrar** [jorgenkg/python-neural-network#7]
Traceback (most recent call last):
  File "/neuralnet.py", line 101, in backpropagation
    input_signals, derivatives = self.update( training_data, trace=True )
  File "/neuralnet.py", line 436, in update
    derivatives.append( self.layers[i][1]( signal, derivative = True ).T )
AttributeError: 'int' object has no attribute 'T'

The issue in this case is linear_function, which returns 1 if derivative = True, and obviously this cannot be transposed.

**Comment by huntrar** [comment]
The simple fix here would be to check the return type for int before transposing, which I have done for my own purposes. Let me know if you would like me to add this fix to my current open PR.

**Comment by jorgenkg** [comment]
I quickly pushed an update to fix the issue. Thanks for the heads-up, @huntrar!
